// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *HomePage → HeroCarouselData*
 */
export interface HomepageDocumentDataHerocarouseldataItem {
  /**
   * HeroCarouselBackground field in *HomePage → HeroCarouselData*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.herocarouseldata[].herocarouselbackground
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  herocarouselbackground: prismic.ImageField<never>;

  /**
   * HeroCarouselTitle field in *HomePage → HeroCarouselData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Slide Title (H2)
   * - **API ID Path**: homepage.herocarouseldata[].herocarouseltitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  herocarouseltitle: prismic.KeyTextField;

  /**
   * HeroCarouselDescription field in *HomePage → HeroCarouselData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut...
   * - **API ID Path**: homepage.herocarouseldata[].herocarouseldescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  herocarouseldescription: prismic.KeyTextField;

  /**
   * HeroCarouselLink field in *HomePage → HeroCarouselData*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Slide Link
   * - **API ID Path**: homepage.herocarouseldata[].herocarousellink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  herocarousellink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

type HomepageDocumentDataSlicesSlice = never;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
  /**
   * HeroCarouselData field in *HomePage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.herocarouseldata[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  herocarouseldata: prismic.GroupField<
    Simplify<HomepageDocumentDataHerocarouseldataItem>
  >;

  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Item in *Carousel → Conference → Primary → CarouselSlide*
 */
export interface CarouselSliceDefaultPrimaryCarouselslideItem {
  /**
   * CarouselSlideBackground field in *Carousel → Conference → Primary → CarouselSlide*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.carouselslide[].carouselslidebackground
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  carouselslidebackground: prismic.ImageField<never>;

  /**
   * CarouselSlideTitle field in *Carousel → Conference → Primary → CarouselSlide*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Slide Title
   * - **API ID Path**: carousel.default.primary.carouselslide[].carouselslidetitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  carouselslidetitle: prismic.KeyTextField;

  /**
   * CarouselSlideDescription field in *Carousel → Conference → Primary → CarouselSlide*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut...
   * - **API ID Path**: carousel.default.primary.carouselslide[].carouselslidedescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  carouselslidedescription: prismic.KeyTextField;

  /**
   * CarouselSlideLink field in *Carousel → Conference → Primary → CarouselSlide*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.carouselslide[].carouselslidelink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  carouselslidelink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * CarouselSlideLocation field in *Carousel → Conference → Primary → CarouselSlide*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Location
   * - **API ID Path**: carousel.default.primary.carouselslide[].carouselslidelocation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  carouselslidelocation: prismic.KeyTextField;

  /**
   * CarouselSlideDate field in *Carousel → Conference → Primary → CarouselSlide*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: Date
   * - **API ID Path**: carousel.default.primary.carouselslide[].carouselslidedate
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  carouselslidedate: prismic.TimestampField;
}

/**
 * Primary content in *Carousel → Conference → Primary*
 */
export interface CarouselSliceDefaultPrimary {
  /**
   * CarouselSlide field in *Carousel → Conference → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.carouselslide[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carouselslide: prismic.GroupField<
    Simplify<CarouselSliceDefaultPrimaryCarouselslideItem>
  >;

  /**
   * CarouselTitle field in *Carousel → Conference → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Carousel Title
   * - **API ID Path**: carousel.default.primary.carouseltitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  carouseltitle: prismic.KeyTextField;

  /**
   * CarouselSubtitle field in *Carousel → Conference → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Carousel Subtitle
   * - **API ID Path**: carousel.default.primary.carouselsubtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  carouselsubtitle: prismic.KeyTextField;

  /**
   * CarouselLink field in *Carousel → Conference → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.carousellink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  carousellink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Conference variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Carousel*
 */
type CarouselSliceVariation = CarouselSliceDefault;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Carousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSlice = prismic.SharedSlice<
  "carousel",
  CarouselSliceVariation
>;

/**
 * Primary content in *SpeedBump → Default → Primary*
 */
export interface SideBySideSliceDefaultPrimary {
  /**
   * SpeedBumpImage field in *SpeedBump → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: side_by_side.default.primary.speedbumpimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  speedbumpimage: prismic.ImageField<never>;

  /**
   * SpeedBumpTitle field in *SpeedBump → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Content Title
   * - **API ID Path**: side_by_side.default.primary.speedbumptitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  speedbumptitle: prismic.KeyTextField;

  /**
   * SpeedBumpDescription field in *SpeedBump → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut...
   * - **API ID Path**: side_by_side.default.primary.speedbumpdescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  speedbumpdescription: prismic.KeyTextField;

  /**
   * SpeedBumpLink field in *SpeedBump → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: side_by_side.default.primary.speedbumplink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  speedbumplink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for SpeedBump Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SideBySideSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SideBySideSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SpeedBump*
 */
type SideBySideSliceVariation = SideBySideSliceDefault;

/**
 * SpeedBump Shared Slice
 *
 * - **API ID**: `side_by_side`
 * - **Description**: SideBySide
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SideBySideSlice = prismic.SharedSlice<
  "side_by_side",
  SideBySideSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataHerocarouseldataItem,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CarouselSlice,
      CarouselSliceDefaultPrimaryCarouselslideItem,
      CarouselSliceDefaultPrimary,
      CarouselSliceVariation,
      CarouselSliceDefault,
      SideBySideSlice,
      SideBySideSliceDefaultPrimary,
      SideBySideSliceVariation,
      SideBySideSliceDefault,
    };
  }
}
