// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ContactPageDocumentDataSlicesSlice = never;

/**
 * Content for ContactPage documents
 */
interface ContactPageDocumentData {
  /**
   * PageImage field in *ContactPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contactPage.pageImage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  pageImage: prismic.ImageField<never>;

  /**
   * PageTitle field in *ContactPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contactPage.pageTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pageTitle: prismic.KeyTextField;

  /**
   * PageContent field in *ContactPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contactPage.pageContent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pageContent: prismic.RichTextField;

  /**
   * Slice Zone field in *ContactPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contactPage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactPageDocumentDataSlicesSlice> /**
   * Meta Title field in *ContactPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contactPage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *ContactPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contactPage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *ContactPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contactPage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * ContactPage document from Prismic
 *
 * - **API ID**: `contactPage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactPageDocumentData>,
    "contactPage",
    Lang
  >;

/**
 * Item in *Footer → FooterAddress*
 */
export interface FooterDocumentDataFooterAddressItem {
  /**
   * FooterAddressLine field in *Footer → FooterAddress*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footerAddress[].footerAddressLine
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footerAddressLine: prismic.KeyTextField;
}

/**
 * Item in *Footer → FooterContact*
 */
export interface FooterDocumentDataFooterContactInfoItem {
  /**
   * FooterContactLine field in *Footer → FooterContact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footerContactInfo[].footerContactLine
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footerContactLine: prismic.KeyTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * FooterAddress field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footerAddress[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footerAddress: prismic.GroupField<
    Simplify<FooterDocumentDataFooterAddressItem>
  >;

  /**
   * FooterContact field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footerContactInfo[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footerContactInfo: prismic.GroupField<
    Simplify<FooterDocumentDataFooterContactInfoItem>
  >;

  /**
   * HelpfulNavLinks field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.helpfulNavLinks
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  helpfulNavLinks: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * SubFooterNavLinks field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.subFooterNavLinks
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  subFooterNavLinks: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * MemberNavLinks field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.memberNavLinks
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  memberNavLinks: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HeaderDocumentDataSlicesSlice = MenuItemSlice;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Slice Zone field in *Header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

/**
 * Item in *HomePage → HeroCarouselData*
 */
export interface HomepageDocumentDataHeroCarouselDataItem {
  /**
   * HeroCarouselBackground field in *HomePage → HeroCarouselData*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroCarouselData[].heroCarouselBackground
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  heroCarouselBackground: prismic.ImageField<never>;

  /**
   * HeroCarouselTitle field in *HomePage → HeroCarouselData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Slide Title (H2)
   * - **API ID Path**: homepage.heroCarouselData[].heroCarouselTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heroCarouselTitle: prismic.KeyTextField;

  /**
   * HeroCarouselDescription field in *HomePage → HeroCarouselData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut...
   * - **API ID Path**: homepage.heroCarouselData[].heroCarouselDescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heroCarouselDescription: prismic.KeyTextField;

  /**
   * HeroCarouselLink field in *HomePage → HeroCarouselData*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Slide Link
   * - **API ID Path**: homepage.heroCarouselData[].heroCarouselLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  heroCarouselLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *HomePage → IntroImageTile*
 */
export interface HomepageDocumentDataIntroImageTileItem {
  /**
   * IntroImage1 field in *HomePage → IntroImageTile*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introImageTile[].introImage1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  introImage1: prismic.ImageField<never>;

  /**
   * introImage2 field in *HomePage → IntroImageTile*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introImageTile[].introImage2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  introImage2: prismic.ImageField<never>;
}

type HomepageDocumentDataSlicesSlice =
  | SpeedBumpSlice
  | SocialCarouselSlice
  | CarouselSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
  /**
   * HeroTitle field in *HomePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heroTitle: prismic.RichTextField;

  /**
   * HeroSubTitle field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroSubTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heroSubTitle: prismic.KeyTextField;

  /**
   * HeroAction field in *HomePage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroAction
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  heroAction: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * HeroCarouselData field in *HomePage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.heroCarouselData[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  heroCarouselData: prismic.GroupField<
    Simplify<HomepageDocumentDataHeroCarouselDataItem>
  >;

  /**
   * NextConferenceInfo field in *HomePage*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.nextConferenceInfo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  nextConferenceInfo: prismic.ContentRelationshipField<"nextConferenceSection">;

  /**
   * IntroHeader field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Our Mission: Excellence in Corrections
   * - **API ID Path**: homepage.introHeader
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  introHeader: prismic.KeyTextField;

  /**
   * IntroDescription field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium...
   * - **API ID Path**: homepage.introDescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  introDescription: prismic.KeyTextField;

  /**
   * IntroAction field in *HomePage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introAction
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  introAction: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * IntroImageTile field in *HomePage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introImageTile[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  introImageTile: prismic.GroupField<
    Simplify<HomepageDocumentDataIntroImageTileItem>
  >;

  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type NextConferenceSectionDocumentDataSlicesSlice = ConferenceCardSlice;

/**
 * Content for NextConferenceSection documents
 */
interface NextConferenceSectionDocumentData {
  /**
   * ConferenceTitle field in *NextConferenceSection*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nextConferenceSection.conferenceTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  conferenceTitle: prismic.KeyTextField;

  /**
   * ConferenceStartDateTime field in *NextConferenceSection*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: nextConferenceSection.conferenceStartDateTime
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  conferenceStartDateTime: prismic.TimestampField;

  /**
   * ConferenceLink field in *NextConferenceSection*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nextConferenceSection.conferenceLink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  conferenceLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * ConferenceEndDateTime field in *NextConferenceSection*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: nextConferenceSection.conferenceEndDateTime
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  conferenceEndDateTime: prismic.TimestampField;

  /**
   * ConferenceGeoPoint field in *NextConferenceSection*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: nextConferenceSection.conferenceGeoPoint
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  conferenceGeoPoint: prismic.GeoPointField;

  /**
   * ConferenceLocation field in *NextConferenceSection*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nextConferenceSection.conferenceLocation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  conferenceLocation: prismic.KeyTextField;

  /**
   * Slice Zone field in *NextConferenceSection*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: nextConferenceSection.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NextConferenceSectionDocumentDataSlicesSlice>;
}

/**
 * NextConferenceSection document from Prismic
 *
 * - **API ID**: `nextConferenceSection`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NextConferenceSectionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NextConferenceSectionDocumentData>,
    "nextConferenceSection",
    Lang
  >;

type TierOnePageDocumentDataSlicesSlice =
  | AccordionSlice
  | LinkTileSlice
  | CarouselSlice
  | SpeedBumpSlice;

type TierOnePageDocumentDataSlices2Slice =
  | SpeedBumpSlice
  | AccordionSlice
  | CarouselSlice
  | SocialCarouselSlice;

/**
 * Content for TierOnePage documents
 */
interface TierOnePageDocumentData {
  /**
   * PageImage field in *TierOnePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tierOnePage.pageImage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  pageImage: prismic.ImageField<never>;

  /**
   * PageTitle field in *TierOnePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tierOnePage.pageTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pageTitle: prismic.KeyTextField;

  /**
   * PageSubTitle field in *TierOnePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tierOnePage.pageSubTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pageSubTitle: prismic.KeyTextField;

  /**
   * PageContent field in *TierOnePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tierOnePage.pageTextContent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pageTextContent: prismic.RichTextField;

  /**
   * Slice Zone field in *TierOnePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tierOnePage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TierOnePageDocumentDataSlicesSlice> /**
   * Meta Title field in *TierOnePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: tierOnePage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *TierOnePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: tierOnePage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *TierOnePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tierOnePage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never> /**
   * Slice Zone field in *TierOnePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tierOnePage.slices2[]
   * - **Tab**: PostContent
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices2: prismic.SliceZone<TierOnePageDocumentDataSlices2Slice>;
}

/**
 * TierOnePage document from Prismic
 *
 * - **API ID**: `tierOnePage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TierOnePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TierOnePageDocumentData>,
    "tierOnePage",
    Lang
  >;

type TierThreePageDocumentDataSlicesSlice = never;

type TierThreePageDocumentDataSlices2Slice =
  | CarouselSlice
  | SpeedBumpSlice
  | AccordionSlice;

/**
 * Content for TierThreePage documents
 */
interface TierThreePageDocumentData {
  /**
   * ParentPage field in *TierThreePage*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: tierThreePage.parentPage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parentPage: prismic.ContentRelationshipField<"tierTwoPage">;

  /**
   * PageImage field in *TierThreePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tierThreePage.pageImage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  pageImage: prismic.ImageField<never>;

  /**
   * PageTitle field in *TierThreePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tierThreePage.pageTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pageTitle: prismic.KeyTextField;

  /**
   * PageSubTitle field in *TierThreePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tierThreePage.pageSubTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pageSubTitle: prismic.KeyTextField;

  /**
   * PageContent field in *TierThreePage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tierThreePage.pageContent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pageContent: prismic.RichTextField;

  /**
   * Hide from Right Menu? field in *TierThreePage*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: tierThreePage.hideFromRightMenu
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hideFromRightMenu: prismic.BooleanField;

  /**
   * Slice Zone field in *TierThreePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tierThreePage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TierThreePageDocumentDataSlicesSlice> /**
   * Meta Title field in *TierThreePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: tierThreePage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *TierThreePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: tierThreePage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *TierThreePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tierThreePage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never> /**
   * Slice Zone field in *TierThreePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tierThreePage.slices2[]
   * - **Tab**: PostContent
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices2: prismic.SliceZone<TierThreePageDocumentDataSlices2Slice>;
}

/**
 * TierThreePage document from Prismic
 *
 * - **API ID**: `tierThreePage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TierThreePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TierThreePageDocumentData>,
    "tierThreePage",
    Lang
  >;

type TierTwoPageDocumentDataSlicesSlice =
  | SpeedBumpSlice
  | CarouselSlice
  | AccordionSlice
  | LinkTileSlice;

type TierTwoPageDocumentDataSlices2Slice =
  | AccordionSlice
  | SpeedBumpSlice
  | CarouselSlice;

/**
 * Content for TierTwoPage documents
 */
interface TierTwoPageDocumentData {
  /**
   * ParentPage field in *TierTwoPage*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: tierTwoPage.parentPage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parentPage: prismic.ContentRelationshipField<"tierOnePage">;

  /**
   * PageImage field in *TierTwoPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tierTwoPage.pageImage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  pageImage: prismic.ImageField<never>;

  /**
   * PageTitle field in *TierTwoPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tierTwoPage.pageTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pageTitle: prismic.KeyTextField;

  /**
   * PageSubTitle field in *TierTwoPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tierTwoPage.pageSubTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pageSubTitle: prismic.KeyTextField;

  /**
   * PageContent field in *TierTwoPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tierTwoPage.pageTextContent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pageTextContent: prismic.RichTextField;

  /**
   * Hide from Right Menu? field in *TierTwoPage*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: tierTwoPage.hideFromRightMenu
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hideFromRightMenu: prismic.BooleanField;

  /**
   * Slice Zone field in *TierTwoPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tierTwoPage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TierTwoPageDocumentDataSlicesSlice> /**
   * Meta Title field in *TierTwoPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: tierTwoPage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *TierTwoPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: tierTwoPage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *TierTwoPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tierTwoPage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never> /**
   * Slice Zone field in *TierTwoPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tierTwoPage.slices2[]
   * - **Tab**: PostContent
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices2: prismic.SliceZone<TierTwoPageDocumentDataSlices2Slice>;
}

/**
 * TierTwoPage document from Prismic
 *
 * - **API ID**: `tierTwoPage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TierTwoPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TierTwoPageDocumentData>,
    "tierTwoPage",
    Lang
  >;

export type AllDocumentTypes =
  | ContactPageDocument
  | FooterDocument
  | HeaderDocument
  | HomepageDocument
  | NextConferenceSectionDocument
  | TierOnePageDocument
  | TierThreePageDocument
  | TierTwoPageDocument;

/**
 * Item in *Accordion → Default → Primary → AccordionItems*
 */
export interface AccordionSliceDefaultPrimaryAccordionItemsItem {
  /**
   * AccordionDescription field in *Accordion → Default → Primary → AccordionItems*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.default.primary.accordionItems[].accordionDescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  accordionDescription: prismic.KeyTextField;

  /**
   * AccordionTitle field in *Accordion → Default → Primary → AccordionItems*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.default.primary.accordionItems[].accordionTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  accordionTitle: prismic.KeyTextField;

  /**
   * AccordionAction field in *Accordion → Default → Primary → AccordionItems*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.default.primary.accordionItems[].accordionAction
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  accordionAction: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Accordion → Default → Primary*
 */
export interface AccordionSliceDefaultPrimary {
  /**
   * AccordionItems field in *Accordion → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.default.primary.accordionItems[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  accordionItems: prismic.GroupField<
    Simplify<AccordionSliceDefaultPrimaryAccordionItemsItem>
  >;
}

/**
 * Default variation for Accordion Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AccordionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Accordion*
 */
type AccordionSliceVariation = AccordionSliceDefault;

/**
 * Accordion Shared Slice
 *
 * - **API ID**: `accordion`
 * - **Description**: Accordion
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSlice = prismic.SharedSlice<
  "accordion",
  AccordionSliceVariation
>;

/**
 * Primary content in *ActionCard → Default → Primary*
 */
export interface ActionCardSliceDefaultPrimary {
  /**
   * CardActions field in *ActionCard → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: action_card.default.primary.cardActions
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cardActions: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * CardTitle field in *ActionCard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: action_card.default.primary.cardTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardTitle: prismic.KeyTextField;

  /**
   * CardDescription field in *ActionCard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: action_card.default.primary.cardDescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardDescription: prismic.KeyTextField;
}

/**
 * Default variation for ActionCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ActionCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ActionCardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ActionCard*
 */
type ActionCardSliceVariation = ActionCardSliceDefault;

/**
 * ActionCard Shared Slice
 *
 * - **API ID**: `action_card`
 * - **Description**: ActionCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ActionCardSlice = prismic.SharedSlice<
  "action_card",
  ActionCardSliceVariation
>;

/**
 * Item in *Carousel → Default → Primary → CarouselSlides*
 */
export interface CarouselSliceDefaultPrimaryCarouselSlidesItem {
  /**
   * CarouselSlideBackground field in *Carousel → Default → Primary → CarouselSlides*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.carouselSlides[].carouselSlideBackground
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  carouselSlideBackground: prismic.ImageField<never>;

  /**
   * CarouselSlideTitle field in *Carousel → Default → Primary → CarouselSlides*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Slide Title
   * - **API ID Path**: carousel.default.primary.carouselSlides[].carouselSlideTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  carouselSlideTitle: prismic.KeyTextField;

  /**
   * CarouselSlideDescription field in *Carousel → Default → Primary → CarouselSlides*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut...
   * - **API ID Path**: carousel.default.primary.carouselSlides[].carouselSlideDescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  carouselSlideDescription: prismic.KeyTextField;

  /**
   * CarouselSlideLink field in *Carousel → Default → Primary → CarouselSlides*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.carouselSlides[].carouselSlideLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  carouselSlideLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Carousel → Default → Primary*
 */
export interface CarouselSliceDefaultPrimary {
  /**
   * CarouselSlides field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.carouselSlides[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carouselSlides: prismic.GroupField<
    Simplify<CarouselSliceDefaultPrimaryCarouselSlidesItem>
  >;

  /**
   * CarouselTitle field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Carousel Title
   * - **API ID Path**: carousel.default.primary.carouselTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  carouselTitle: prismic.KeyTextField;

  /**
   * CarouselSubtitle field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Carousel Subtitle
   * - **API ID Path**: carousel.default.primary.carouselSubTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  carouselSubTitle: prismic.KeyTextField;

  /**
   * CarouselLink field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.carouselLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  carouselLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * CarouselTag field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.carouselTag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  carouselTag: prismic.KeyTextField;
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Carousel*
 */
type CarouselSliceVariation = CarouselSliceDefault;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Carousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSlice = prismic.SharedSlice<
  "carousel",
  CarouselSliceVariation
>;

/**
 * Primary content in *ConferenceCard → Default → Primary*
 */
export interface ConferenceCardSliceDefaultPrimary {
  /**
   * ConferenceCardImage field in *ConferenceCard → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: conference_card.default.primary.conferenceCardImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  conferenceCardImage: prismic.ImageField<never>;

  /**
   * ConferenceCardTitle field in *ConferenceCard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: conference_card.default.primary.conferenceCardTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  conferenceCardTitle: prismic.KeyTextField;

  /**
   * conferenceCardDesc field in *ConferenceCard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: conference_card.default.primary.conferenceCardDesc
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  conferenceCardDesc: prismic.KeyTextField;

  /**
   * conferenceCardLink field in *ConferenceCard → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: conference_card.default.primary.conferenceCardLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  conferenceCardLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for ConferenceCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ConferenceCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ConferenceCardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ConferenceCard*
 */
type ConferenceCardSliceVariation = ConferenceCardSliceDefault;

/**
 * ConferenceCard Shared Slice
 *
 * - **API ID**: `conference_card`
 * - **Description**: ConferenceCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ConferenceCardSlice = prismic.SharedSlice<
  "conference_card",
  ConferenceCardSliceVariation
>;

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Primary content in *LinkCard → Default → Primary*
 */
export interface LinkCardSliceDefaultPrimary {
  /**
   * CardTitle field in *LinkCard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_card.default.primary.cardTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardTitle: prismic.KeyTextField;

  /**
   * CardDescription field in *LinkCard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_card.default.primary.cardDescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardDescription: prismic.KeyTextField;

  /**
   * CardLink field in *LinkCard → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_card.default.primary.cardLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cardLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for LinkCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkCardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LinkCard*
 */
type LinkCardSliceVariation = LinkCardSliceDefault;

/**
 * LinkCard Shared Slice
 *
 * - **API ID**: `link_card`
 * - **Description**: LinkCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkCardSlice = prismic.SharedSlice<
  "link_card",
  LinkCardSliceVariation
>;

/**
 * Primary content in *LinkTile → Default → Primary*
 */
export interface LinkTileSliceDefaultPrimary {
  /**
   * TileImage field in *LinkTile → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: link_tile.default.primary.tileImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  tileImage: prismic.ImageField<never>;

  /**
   * TileTitle field in *LinkTile → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_tile.default.primary.tileTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tileTitle: prismic.KeyTextField;

  /**
   * TileDescription field in *LinkTile → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_tile.default.primary.tileDescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tileDescription: prismic.KeyTextField;

  /**
   * TileLink field in *LinkTile → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_tile.default.primary.tileLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tileLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for LinkTile Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkTileSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkTileSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LinkTile*
 */
type LinkTileSliceVariation = LinkTileSliceDefault;

/**
 * LinkTile Shared Slice
 *
 * - **API ID**: `link_tile`
 * - **Description**: LinkTile
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkTileSlice = prismic.SharedSlice<
  "link_tile",
  LinkTileSliceVariation
>;

/**
 * Item in *MenuItem → Default → Primary → TierTwoMenuItems*
 */
export interface MenuItemSliceDefaultPrimaryTierTwoMenuItemsItem {
  /**
   * TierTwoMenuIcon field in *MenuItem → Default → Primary → TierTwoMenuItems*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.tierTwoMenuItems[].tierTwoMenuIcon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  tierTwoMenuIcon: prismic.ImageField<never>;

  /**
   * TierTwoMenuDesc field in *MenuItem → Default → Primary → TierTwoMenuItems*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.tierTwoMenuItems[].tierTwoMenuDesc
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tierTwoMenuDesc: prismic.KeyTextField;

  /**
   * TierTwoMenuLink field in *MenuItem → Default → Primary → TierTwoMenuItems*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.tierTwoMenuItems[].tierTwoMenuLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tierTwoMenuLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *MenuItem → Default → Primary*
 */
export interface MenuItemSliceDefaultPrimary {
  /**
   * TierOneLink field in *MenuItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.tierOneLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tierOneLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * TierTwoMenuItems field in *MenuItem → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.tierTwoMenuItems[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tierTwoMenuItems: prismic.GroupField<
    Simplify<MenuItemSliceDefaultPrimaryTierTwoMenuItemsItem>
  >;

  /**
   * FeaturedMenuImage field in *MenuItem → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.featuredMenuImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featuredMenuImage: prismic.ImageField<never>;

  /**
   * FeaturedMenuLink field in *MenuItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.default.primary.featuredMenuLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  featuredMenuLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for MenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MenuItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MenuItem*
 */
type MenuItemSliceVariation = MenuItemSliceDefault;

/**
 * MenuItem Shared Slice
 *
 * - **API ID**: `menu_item`
 * - **Description**: MenuItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSlice = prismic.SharedSlice<
  "menu_item",
  MenuItemSliceVariation
>;

/**
 * Primary content in *SocialCarousel → Default → Primary*
 */
export interface SocialCarouselSliceDefaultPrimary {
  /**
   * SocialCarouselTitle field in *SocialCarousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_carousel.default.primary.socialCarouselTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  socialCarouselTitle: prismic.KeyTextField;

  /**
   * SocialCarouselDescription field in *SocialCarousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_carousel.default.primary.socialCarouselDescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  socialCarouselDescription: prismic.KeyTextField;

  /**
   * SocialCarouselLink field in *SocialCarousel → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: social_carousel.default.primary.socialCarouselLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  socialCarouselLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for SocialCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SocialCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SocialCarousel*
 */
type SocialCarouselSliceVariation = SocialCarouselSliceDefault;

/**
 * SocialCarousel Shared Slice
 *
 * - **API ID**: `social_carousel`
 * - **Description**: SocialCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialCarouselSlice = prismic.SharedSlice<
  "social_carousel",
  SocialCarouselSliceVariation
>;

/**
 * Primary content in *SpeedBump → Default → Primary*
 */
export interface SpeedBumpSliceDefaultPrimary {
  /**
   * SpeedBumpImage field in *SpeedBump → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: speedBump.default.primary.speedBumpImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  speedBumpImage: prismic.ImageField<never>;

  /**
   * SpeedBumpTitle field in *SpeedBump → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Content Title
   * - **API ID Path**: speedBump.default.primary.speedBumpTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  speedBumpTitle: prismic.KeyTextField;

  /**
   * SpeedBumpDescription field in *SpeedBump → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut...
   * - **API ID Path**: speedBump.default.primary.speedBumpDescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  speedBumpDescription: prismic.KeyTextField;

  /**
   * SpeedBumpLinks field in *SpeedBump → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: speedBump.default.primary.speedBumpLinks
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  speedBumpLinks: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * SpeedBumpTheme field in *SpeedBump → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: light
   * - **API ID Path**: speedBump.default.primary.speedBumpTheme
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  speedBumpTheme: prismic.SelectField<"light" | "dark", "filled">;

  /**
   * SpeedBumpLinkPosition field in *SpeedBump → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: bottom
   * - **API ID Path**: speedBump.default.primary.speedBumpLinkPosition
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  speedBumpLinkPosition: prismic.SelectField<"bottom" | "right", "filled">;
}

/**
 * Default variation for SpeedBump Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpeedBumpSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SpeedBumpSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SpeedBump*
 */
type SpeedBumpSliceVariation = SpeedBumpSliceDefault;

/**
 * SpeedBump Shared Slice
 *
 * - **API ID**: `speedBump`
 * - **Description**: SpeedBump
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpeedBumpSlice = prismic.SharedSlice<
  "speedBump",
  SpeedBumpSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContactPageDocument,
      ContactPageDocumentData,
      ContactPageDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataFooterAddressItem,
      FooterDocumentDataFooterContactInfoItem,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataHeroCarouselDataItem,
      HomepageDocumentDataIntroImageTileItem,
      HomepageDocumentDataSlicesSlice,
      NextConferenceSectionDocument,
      NextConferenceSectionDocumentData,
      NextConferenceSectionDocumentDataSlicesSlice,
      TierOnePageDocument,
      TierOnePageDocumentData,
      TierOnePageDocumentDataSlicesSlice,
      TierOnePageDocumentDataSlices2Slice,
      TierThreePageDocument,
      TierThreePageDocumentData,
      TierThreePageDocumentDataSlicesSlice,
      TierThreePageDocumentDataSlices2Slice,
      TierTwoPageDocument,
      TierTwoPageDocumentData,
      TierTwoPageDocumentDataSlicesSlice,
      TierTwoPageDocumentDataSlices2Slice,
      AllDocumentTypes,
      AccordionSlice,
      AccordionSliceDefaultPrimaryAccordionItemsItem,
      AccordionSliceDefaultPrimary,
      AccordionSliceVariation,
      AccordionSliceDefault,
      ActionCardSlice,
      ActionCardSliceDefaultPrimary,
      ActionCardSliceVariation,
      ActionCardSliceDefault,
      CarouselSlice,
      CarouselSliceDefaultPrimaryCarouselSlidesItem,
      CarouselSliceDefaultPrimary,
      CarouselSliceVariation,
      CarouselSliceDefault,
      ConferenceCardSlice,
      ConferenceCardSliceDefaultPrimary,
      ConferenceCardSliceVariation,
      ConferenceCardSliceDefault,
      ContactFormSlice,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      LinkCardSlice,
      LinkCardSliceDefaultPrimary,
      LinkCardSliceVariation,
      LinkCardSliceDefault,
      LinkTileSlice,
      LinkTileSliceDefaultPrimary,
      LinkTileSliceVariation,
      LinkTileSliceDefault,
      MenuItemSlice,
      MenuItemSliceDefaultPrimaryTierTwoMenuItemsItem,
      MenuItemSliceDefaultPrimary,
      MenuItemSliceVariation,
      MenuItemSliceDefault,
      SocialCarouselSlice,
      SocialCarouselSliceDefaultPrimary,
      SocialCarouselSliceVariation,
      SocialCarouselSliceDefault,
      SpeedBumpSlice,
      SpeedBumpSliceDefaultPrimary,
      SpeedBumpSliceVariation,
      SpeedBumpSliceDefault,
    };
  }
}
