import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { getFooterData } from "./actions/getLayoutData";
import Header from "@/components/header";
import { FooterDocument } from "../../prismicio-types";
import Footer from "@/components/footer";

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    let footerInfo: FooterDocument<string> | null = null;

    const fetchFooterInfo = async () => {
        try {
            footerInfo = await getFooterData();
        } catch (err) {
            console.error(err);
        }
    };

    await Promise.allSettled([fetchFooterInfo()]);

    return (
        <html lang="en">
            <body
                className={`${poppins.variable} antialiased [font-family:Poppins]`}
            >
                <Header />
                <div className="mt-17">{children}</div>
                {footerInfo && (
                    <Footer {...(footerInfo as FooterDocument<string>).data} />
                )}
            </body>
        </html>
    );
}
