import type { Metadata } from "next";
import "./globals.css";
import { getFooterData, getHeaderData } from "./actions/getLayoutData";
import Header from "@/components/header";
import { MenuItemSlice } from "../../prismicio-types";
import Footer, { FooterProps } from "@/components/footer";
import { gillSans } from "./fonts/GillSans";
import CacheProvider from "react-inlinesvg/provider";
import { HydrationBoundary } from "jotai-ssr";
import { SearchDialog } from "./components/SearchDialog";
import { getSearchData, PageData } from "./actions/getSearchData";
import { pageInfoAtom } from "./atoms/pageInfoAtom";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let footerInfo: FooterProps | null = null;
  let headerInfo: MenuItemSlice[] | null = null;
  let pageInfo: PageData[] | null = null;

  const fetchFooterInfo = async () => {
    try {
      footerInfo = await getFooterData();
    } catch (err) {
      console.error(err);
    }
  };

  const fetchHeaderInfo = async () => {
    try {
      const result = await getHeaderData();

      headerInfo = result?.data || null;
    } catch (err) {
      console.error(err);
    }
  };

  const fetchPageInfo = async () => {
    try {
      const result = await getSearchData();
      pageInfo = result || null;
    } catch (err) {
      console.error(err);
    }
  };

  await Promise.allSettled([
    fetchFooterInfo(),
    fetchHeaderInfo(),
    fetchPageInfo(),
  ]);

  return (
    <html lang="en" className="w-screen overflow-x-clip">
      <body
        className={`${gillSans.variable} [font-family:GillSans] antialiased`}
      >
        <HydrationBoundary hydrateAtoms={[[pageInfoAtom, pageInfo || []]]}>
          <CacheProvider>
            {headerInfo && <Header data={headerInfo} />}
          </CacheProvider>
          <div className="mt-17">{children}</div>
          {footerInfo && <Footer data={footerInfo} />}
          <SearchDialog />
        </HydrationBoundary>
      </body>
    </html>
  );
}
